name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  test_wpa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.2'
        coverage: none

    - name: Install dependencies
      run: |
        composer install
        npm install
        npm run build

    - name: Setup WP Snapshots
      run: ./vendor/bin/wpsnapshots configure 10up --aws_key=${{ secrets.AWS_ACCESS_KEY }} --aws_secret=${{ secrets.SECRET_ACCESS_KEY }} --user_name=wp-acceptance --user_email=travis@10up.com

    - name: Test
      run: ./vendor/bin/wpacceptance run --screenshot_on_failure

    - name: Pre check
      run: ls

    - uses: actions/upload-artifact@v2
      with:
        path: screenshots/
